baseurl = "https://nyu.data-bootcamp.com/"
languageCode = "en-us"
title = "Data Bootcamp"
metaDataFormat = "yaml"
theme = "hyde-y"

[params]
    topline = "Data + Python @ NYU Stern"
    brand = "Data Bootcamp"
    footline = "A product of the NYU Python Factory @ NYU Stern"

    #Â Sidebar position
    sidebar = "true"  # false, true, "left", "right"
    home = "Home"
    highlight = "tomorrow"
    googleAnalytics = "UA-91442796-1"
